# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: kubernetes
name: core
version: 0.1.0
readme: README.md
authors:
  - Ansible (github.com/ansible-collections)
description: Kubernetes Collection for Ansible
license_file: LICENSE
tags:
# tags so people can search for collections https://galaxy.ansible.com/search
# tags are all lower-case, no spaces, no dashes.
  - kubernetes
repository: https://github.com/ansible-collections/kubernetes.core
#documentation: https://github.com/ansible-collection-migration/community.REPO_NAME/tree/main/docs
homepage: https://github.com/ansible-collections/kubernetes.core
issues: https://github.com/ansible-collections/kubernetes.core/issues
build_ignore:
# https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#ignoring-files-and-folders
  - .gitignore
  - changelogs/.plugin-cache.yaml
