[tox]
minversion = 1.4.2
envlist = linters
skipsdist = True

[testenv]
deps = -r{toxinidir}/requirements.txt
       -r{toxinidir}/test-requirements.txt
install_command = pip install {opts} {packages}

[testenv:black]
deps = black
commands =
  black {toxinidir}/plugins {toxinidir}/tests/unit/

[testenv:linters]
install_command = pip install {opts} {packages}
deps =
  yamllint
  flake8
commands =
  set -e
  yamllint {toxinidir}
  flake8 {posargs} {toxinidir}/plugins {toxinidir}/tests/unit/

[flake8]
exclude = .git,.tox,tests/unit/compat/,tests/output/
