---
deprecated_features:
  - helm - the ``status.values`` return value has been deprecated and will be removed in version 8.0.0.
    Use ``status.release_values`` instead (https://github.com/ansible-collections/kubernetes.core/issues/1239).
  - helm_info - the ``status.values`` return value has been deprecated and will be removed in version 8.0.0.
    Use ``status.release_values`` instead (https://github.com/ansible-collections/kubernetes.core/issues/1239).
