---
- name: Prepare
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core

  tasks:
    - name: Include drain.yml
      include_tasks:
        file: tasks/drain.yml
    
    - name: Include taint.yml
      include_tasks:
        file: tasks/taint.yml
