name: Unit tests
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
      - stable-*

jobs:
  unit-source:
    uses: abikouo/github_actions/.github/workflows/unit_source.yml@unit_sanity_2.21
